version: 2.1
commands:
  destroy_environment:
    steps:
      - run:
          name: Destroy Environment
          command:  |
            aws cloudformation delete-stack --stack-name prod-${CIRCLE_WORKFLOW_ID}
jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Ensure backend infrastructure exist
          command: |
            pwd
            ls -la
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name prod-${CIRCLE_WORKFLOW_ID}
      - run:
          name: simulate error
          command: |
            return 1
      - destroy_environment
          when: on_fail
workflows:
  myworkflow:
    jobs:
      - create_infrastructure

## What Do I Need for This Job?
#1- A reusable command to handle the work of destroying the green infrastructure.
#2- In the command, a step to delete the stack using whatever name we defined when creating the stack.
#3- A job with an image that can handle AWS CLI commands.
#4- A step that simulates a failed smoke test or any other failure (exit with non-zero).
#5- A step that uses our reusable command with a condition to run only when something failed.
#6- A workflow that runs our job.